.TH "include Directory Reference" 3 "Sun May 29 2022" "Version 0.1" "Aurora" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBlOsc\&.h\fP"
.br
.ti -1c
.RI "file \fBConv\&.h\fP"
.br
.ti -1c
.RI "file \fBDel\&.h\fP"
.br
.ti -1c
.RI "file \fBEnv\&.h\fP"
.br
.ti -1c
.RI "file \fBEq\&.h\fP"
.br
.ti -1c
.RI "file \fBFFT\&.h\fP"
.br
.ti -1c
.RI "file \fBFil\&.h\fP"
.br
.ti -1c
.RI "file \fBFourPole\&.h\fP"
.br
.ti -1c
.RI "file \fBFunc\&.h\fP"
.br
.ti -1c
.RI "file \fBOnePole\&.h\fP"
.br
.ti -1c
.RI "file \fBOsc\&.h\fP"
.br
.ti -1c
.RI "file \fBQuad\&.h\fP"
.br
.ti -1c
.RI "file \fBSndBase\&.h\fP"
.br
.ti -1c
.RI "file \fBSpecBase\&.h\fP"
.br
.ti -1c
.RI "file \fBSpecPitch\&.h\fP"
.br
.ti -1c
.RI "file \fBSpecPlay\&.h\fP"
.br
.ti -1c
.RI "file \fBSpecShift\&.h\fP"
.br
.ti -1c
.RI "file \fBSpecStream\&.h\fP"
.br
.ti -1c
.RI "file \fBTwoPole\&.h\fP"
.br
.ti -1c
.RI "file \fBWave\&.h\fP"
.br
.in -1c
