.TH "include Directory Reference" 3 "Fri Dec 3 2021" "Version 0.1" "Aurora" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBlOsc\&.h\fP"
.br
.ti -1c
.RI "file \fBConv\&.h\fP"
.br
.ti -1c
.RI "file \fBDel\&.h\fP"
.br
.ti -1c
.RI "file \fBEnv\&.h\fP"
.br
.ti -1c
.RI "file \fBFFT\&.h\fP"
.br
.ti -1c
.RI "file \fBFourPole\&.h\fP"
.br
.ti -1c
.RI "file \fBFunc\&.h\fP"
.br
.ti -1c
.RI "file \fBOnePole\&.h\fP"
.br
.ti -1c
.RI "file \fBOsc\&.h\fP"
.br
.ti -1c
.RI "file \fBSndBase\&.h\fP"
.br
.ti -1c
.RI "file \fBTwoPole\&.h\fP"
.br
.in -1c
