.TH "Aurora::Env< S, FN >" 3 "Sun May 29 2022" "Version 0.1" "Aurora" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Aurora::Env< S, FN >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Env\&.h>\fP
.PP
Inherits \fBAurora::SndBase< S >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEnv\fP (std::function< S(double, S, S)> f, S rt, S \fBfs\fP=\fBdef_sr\fP, std::size_t \fBvsize\fP=\fBdef_vsize\fP)"
.br
.ti -1c
.RI "\fBEnv\fP (S &a, S &b, S &c, S rt, S \fBfs\fP=\fBdef_sr\fP, std::size_t \fBvsize\fP=\fBdef_vsize\fP)"
.br
.ti -1c
.RI "void \fBrelease\fP (S t)"
.br
.ti -1c
.RI "S \fBrelease\fP ()"
.br
.ti -1c
.RI "void \fBretrigger\fP ()"
.br
.ti -1c
.RI "const std::vector< S > & \fBoperator()\fP (bool gate)"
.br
.ti -1c
.RI "const std::vector< S > & \fBoperator()\fP (S offs, S scal, bool gate)"
.br
.ti -1c
.RI "const std::vector< S > & \fBoperator()\fP (const std::vector< S > &in, bool gate)"
.br
.ti -1c
.RI "S \fBfs\fP () const"
.br
.ti -1c
.RI "void \fBreset\fP (S \fBfs\fP)"
.br
.ti -1c
.RI "void \fBfunc\fP (const std::function< S(double, S, S)> f)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename S, S(*)(S, S, S, double, S, S) FN = ads>
.br
class Aurora::Env< S, FN >"\fBEnv\fP class 
.br
Generic envelope 
.br
S: sample type 
.br
FN: envelope function 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename S , S(*)(S, S, S, double, S, S) FN = ads> \fBAurora::Env\fP< S, FN >::Env (std::function< S(double, S, S)> f, S rt, S fs = \fC\fBdef_sr\fP\fP, std::size_t vsize = \fC\fBdef_vsize\fP\fP)\fC [inline]\fP"
Constructor 
.br
f: envelope function 
.br
rt: release time 
.br
fs: sampling rate 
.br
vsize: signal vector size 
.SS "template<typename S , S(*)(S, S, S, double, S, S) FN = ads> \fBAurora::Env\fP< S, FN >::Env (S & a, S & b, S & c, S rt, S fs = \fC\fBdef_sr\fP\fP, std::size_t vsize = \fC\fBdef_vsize\fP\fP)\fC [inline]\fP"
Constructor 
.br
a: env fn parameter 1 
.br
b: env fn parameter 2 
.br
c: env fn parameter 3
.br
rt: release time 
.br
fs: sampling rate 
.br
vsize: signal vector size 
.SH "Member Function Documentation"
.PP 
.SS "template<typename S , S(*)(S, S, S, double, S, S) FN = ads> S \fBAurora::Env\fP< S, FN >::fs () const\fC [inline]\fP"
Sampling rate query 
.br
returns sampling rate 
.SS "template<typename S , S(*)(S, S, S, double, S, S) FN = ads> void \fBAurora::Env\fP< S, FN >::func (const std::function< S(double, S, S)> f)\fC [inline]\fP"
set the envelope function 
.br
f: envelope function to be used 
.SS "template<typename S , S(*)(S, S, S, double, S, S) FN = ads> const std::vector< S > & \fBAurora::Env\fP< S, FN >::operator() (bool gate)\fC [inline]\fP"
Envelope 
.br
gate: envelope gate 
.SS "template<typename S , S(*)(S, S, S, double, S, S) FN = ads> const std::vector< S > & \fBAurora::Env\fP< S, FN >::operator() (const std::vector< S > & in, bool gate)\fC [inline]\fP"
Envelope 
.br
in: input signal gate: envelope gate 
.SS "template<typename S , S(*)(S, S, S, double, S, S) FN = ads> const std::vector< S > & \fBAurora::Env\fP< S, FN >::operator() (S offs, S scal, bool gate)\fC [inline]\fP"
Envelope 
.br
offs: sig offset scal: sig scale gate: envelope gate 
.SS "template<typename S , S(*)(S, S, S, double, S, S) FN = ads> S \fBAurora::Env\fP< S, FN >::release ()\fC [inline]\fP"

.SS "template<typename S , S(*)(S, S, S, double, S, S) FN = ads> void \fBAurora::Env\fP< S, FN >::release (S t)\fC [inline]\fP"
Release time setter rt: release time 
.SS "template<typename S , S(*)(S, S, S, double, S, S) FN = ads> void \fBAurora::Env\fP< S, FN >::reset (S fs)\fC [inline]\fP"
reset the envelope 
.br
fs: sampling rate 
.SS "template<typename S , S(*)(S, S, S, double, S, S) FN = ads> void \fBAurora::Env\fP< S, FN >::retrigger ()\fC [inline]\fP"
Retrigger 

.SH "Author"
.PP 
Generated automatically by Doxygen for Aurora from the source code\&.
