.TH "Aurora::BlOsc< S, FN >" 3 "Sun May 29 2022" "Version 0.1" "Aurora" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Aurora::BlOsc< S, FN >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BlOsc\&.h>\fP
.PP
Inherits \fBAurora::Osc< S, lookupi< S > >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlOsc\fP (const \fBTableSet\fP< S > *t, S \fBfs\fP=(S) \fBdef_sr\fP, std::size_t \fBvsize\fP=\fBdef_vsize\fP)"
.br
.ti -1c
.RI "void \fBwaveset\fP (const \fBTableSet\fP< S > *t)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename S, S(*)(double, const std::vector< S > *) FN = lookupi<S>>
.br
class Aurora::BlOsc< S, FN >"\fBBlOsc\fP class 
.br
Bandlimited wavetable oscillator\&. 
.br
S: sample type 
.br
FN: oscillator function 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename S , S(*)(double, const std::vector< S > *) FN = lookupi<S>> \fBAurora::BlOsc\fP< S, FN >::BlOsc (const \fBTableSet\fP< S > * t, S fs = \fC(S)\fBdef_sr\fP\fP, std::size_t vsize = \fC\fBdef_vsize\fP\fP)\fC [inline]\fP"
Constructor 
.br
t: wavetable set 
.br
fs: sampling rate 
.br
vsize: vector size 
.SH "Member Function Documentation"
.PP 
.SS "template<typename S , S(*)(double, const std::vector< S > *) FN = lookupi<S>> void \fBAurora::BlOsc\fP< S, FN >::waveset (const \fBTableSet\fP< S > * t)\fC [inline]\fP"
Change the wavetable set t: wavetable set 

.SH "Author"
.PP 
Generated automatically by Doxygen for Aurora from the source code\&.
