.TH "Aurora::OnePole< S >" 3 "Sun May 29 2022" "Version 0.1" "Aurora" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Aurora::OnePole< S >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OnePole\&.h>\fP
.PP
Inherits \fBAurora::SndBase< S >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOnePole\fP (S fs=\fBdef_sr\fP, int \fBvsize\fP=\fBdef_vsize\fP)"
.br
.ti -1c
.RI "const std::vector< S > & \fBoperator()\fP (const std::vector< S > &in, S f)"
.br
.ti -1c
.RI "const std::vector< S > & \fBoperator()\fP (const std::vector< S > &in, const std::vector< S > &f)"
.br
.ti -1c
.RI "void \fBreset\fP (S fs)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename S>
.br
class Aurora::OnePole< S >"\fBOnePole\fP class 
.br
First-order lowpass filter 
.br
S: sample type 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename S > \fBAurora::OnePole\fP< S >::OnePole (S fs = \fC\fBdef_sr\fP\fP, int vsize = \fC\fBdef_vsize\fP\fP)\fC [inline]\fP"
Constructor 
.br
fs: sampling rate 
.br
vsize: vector size 
.SH "Member Function Documentation"
.PP 
.SS "template<typename S > const std::vector< S > & \fBAurora::OnePole\fP< S >::operator() (const std::vector< S > & in, const std::vector< S > & f)\fC [inline]\fP"
Filter 
.br
in: input 
.br
f: cutoff frequency 
.br

.SS "template<typename S > const std::vector< S > & \fBAurora::OnePole\fP< S >::operator() (const std::vector< S > & in, S f)\fC [inline]\fP"
Filter 
.br
in: input 
.br
f: cutoff frequency 
.br

.SS "template<typename S > void \fBAurora::OnePole\fP< S >::reset (S fs)\fC [inline]\fP"
reset the filter 
.br
 fs: sampling rate 

.SH "Author"
.PP 
Generated automatically by Doxygen for Aurora from the source code\&.
