.TH "Aurora::FourPole< S >" 3 "Sun May 29 2022" "Version 0.1" "Aurora" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Aurora::FourPole< S >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FourPole\&.h>\fP
.PP
Inherits \fBAurora::SndBase< S >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFourPole\fP (S sr=\fBdef_sr\fP, int \fBvsize\fP=\fBdef_vsize\fP)"
.br
.ti -1c
.RI "const std::vector< S > & \fBoperator()\fP (const std::vector< S > &in, S f, S r)"
.br
.ti -1c
.RI "const std::vector< S > & \fBoperator()\fP (const std::vector< S > &in, const std::vector< S > &f, S r)"
.br
.ti -1c
.RI "void \fBreset\fP (S fs)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename S>
.br
class Aurora::FourPole< S >"\fBFourPole\fP class 
.br
4-pole lowpass filter 
.br
S: sample type 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename S > \fBAurora::FourPole\fP< S >::FourPole (S sr = \fC\fBdef_sr\fP\fP, int vsize = \fC\fBdef_vsize\fP\fP)\fC [inline]\fP"
Constructor 
.br
sr: sampling rate 
.br
vsize: vector size 
.SH "Member Function Documentation"
.PP 
.SS "template<typename S > const std::vector< S > & \fBAurora::FourPole\fP< S >::operator() (const std::vector< S > & in, const std::vector< S > & f, S r)\fC [inline]\fP"
Filter 
.br
in: input 
.br
f: cutoff frequency 
.br
r: resonance (0-1) 
.SS "template<typename S > const std::vector< S > & \fBAurora::FourPole\fP< S >::operator() (const std::vector< S > & in, S f, S r)\fC [inline]\fP"
Filter 
.br
in: input 
.br
f: cutoff frequency 
.br
r: resonance (0-1) 
.SS "template<typename S > void \fBAurora::FourPole\fP< S >::reset (S fs)\fC [inline]\fP"
reset the filter 
.br
fs: sampling rate 

.SH "Author"
.PP 
Generated automatically by Doxygen for Aurora from the source code\&.
