.TH "Aurora::BinOp< S, OP >" 3 "Sun May 29 2022" "Version 0.1" "Aurora" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Aurora::BinOp< S, OP >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SndBase\&.h>\fP
.PP
Inherits \fBAurora::SndBase< S >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBinOp\fP (std::size_t \fBvsize\fP=\fBdef_vsize\fP)"
.br
.ti -1c
.RI "const std::vector< S > & \fBoperator()\fP (S a, const std::vector< S > &s)"
.br
.ti -1c
.RI "const std::vector< S > & \fBoperator()\fP (const std::vector< S > &s, S a)"
.br
.ti -1c
.RI "const std::vector< S > & \fBoperator()\fP (const std::vector< S > &s1, const std::vector< S > &s2)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename S, S(*)(S, S) OP>
.br
class Aurora::BinOp< S, OP >"\fBBinOp\fP class 
.br
Binary operations 
.br
OP: binary operation function 
.br
S: sample type 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename S , S(*)(S, S) OP> \fBAurora::BinOp\fP< S, OP >::BinOp (std::size_t vsize = \fC\fBdef_vsize\fP\fP)\fC [inline]\fP"
Constructor 
.br
vsize: signal vector size 
.SH "Member Function Documentation"
.PP 
.SS "template<typename S , S(*)(S, S) OP> const std::vector< S > & \fBAurora::BinOp\fP< S, OP >::operator() (const std::vector< S > & s, S a)\fC [inline]\fP"
Binary operation 
.br
s: signal input 
.br
a: scalar input 
.br
returns reference to object signal vector 
.SS "template<typename S , S(*)(S, S) OP> const std::vector< S > & \fBAurora::BinOp\fP< S, OP >::operator() (const std::vector< S > & s1, const std::vector< S > & s2)\fC [inline]\fP"
Binary operation 
.br
s1: signal input 1 
.br
s2: signal input 2 
.br
returns reference to object signal vector 
.SS "template<typename S , S(*)(S, S) OP> const std::vector< S > & \fBAurora::BinOp\fP< S, OP >::operator() (S a, const std::vector< S > & s)\fC [inline]\fP"
Binary operation 
.br
a: scalar input 
.br
s: signal input 
.br
returns reference to object signal vector 

.SH "Author"
.PP 
Generated automatically by Doxygen for Aurora from the source code\&.
