.TH "Aurora::TableSet< S >" 3 "Sun May 29 2022" "Version 0.1" "Aurora" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Aurora::TableSet< S >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BlOsc\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTableSet\fP (uint32_t type, S fs=\fBdef_sr\fP, std::size_t len=\fBdef_ftlen\fP)"
.br
.ti -1c
.RI "\fBTableSet\fP (const std::vector< S > &src, S b=\fBdef_base\fP, S fs=\fBdef_sr\fP)"
.br
.ti -1c
.RI "const std::vector< S > & \fBfunc\fP (S f) const"
.br
.ti -1c
.RI "void \fBreset\fP (uint32_t type, S fs, std::size_t len=\fBdef_ftlen\fP)"
.br
.ti -1c
.RI "void \fBreset\fP (const std::vector< S > &src, S b, S fs)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename S>
.br
class Aurora::TableSet< S >"\fBTableSet\fP class 
.br
Creates a set of tables for \fBBlOsc\fP\&. 
.br
S: sample type 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename S > \fBAurora::TableSet\fP< S >::TableSet (uint32_t type, S fs = \fC\fBdef_sr\fP\fP, std::size_t len = \fC\fBdef_ftlen\fP\fP)\fC [inline]\fP"
Constructor 
.br
type: wave type (SAW, SQUARE, TRIANGLE, PULSE) 
.br
fs: sampling rate for which these will be built 
.br
len: table length 
.SS "template<typename S > \fBAurora::TableSet\fP< S >::TableSet (const std::vector< S > & src, S b = \fC\fBdef_base\fP\fP, S fs = \fC\fBdef_sr\fP\fP)\fC [inline]\fP"
Constructor 
.br
src: source wave table 
.br
b: source table base frequency 
.br
fs: source table sampling rate 
.SH "Member Function Documentation"
.PP 
.SS "template<typename S > const std::vector< S > & \fBAurora::TableSet\fP< S >::func (S f) const\fC [inline]\fP"
table selection 
.br
f: fundamental frequency used for playback 
.SS "template<typename S > void \fBAurora::TableSet\fP< S >::reset (const std::vector< S > & src, S b, S fs)\fC [inline]\fP"
reset the table set 
.br
src: source wave table 
.br
b: source table base frequency 
.br
fs: source table sampling rate 
.br
tlen: table size 
.SS "template<typename S > void \fBAurora::TableSet\fP< S >::reset (uint32_t type, S fs, std::size_t len = \fC\fBdef_ftlen\fP\fP)\fC [inline]\fP"
reset the table set 
.br
type: wave type (SAW, SQUARE, TRIANGLE, PULSE) 
.br
fs: sampling rate for which these will be built tlen: table size 

.SH "Author"
.PP 
Generated automatically by Doxygen for Aurora from the source code\&.
