.TH "Aurora::IR< S >" 3 "Sun May 29 2022" "Version 0.1" "Aurora" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Aurora::IR< S >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Conv\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIR\fP (const std::vector< S > &s, std::size_t \fBpsize\fP=\fBdef_psize\fP)"
.br
.ti -1c
.RI "const std::vector< std::vector< std::complex< S > > > & \fBspectrum\fP () const"
.br
.ti -1c
.RI "const std::size_t \fBpsize\fP () const"
.br
.ti -1c
.RI "const std::size_t \fBnparts\fP () const"
.br
.ti -1c
.RI "void \fBreset\fP (const std::vector< S > &s, std::size_t \fBpsize\fP=\fBdef_psize\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename S>
.br
class Aurora::IR< S >"\fBIR\fP class 
.br
Impulse response table 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename S > \fBAurora::IR\fP< S >::IR (const std::vector< S > & s, std::size_t psize = \fC\fBdef_psize\fP\fP)\fC [inline]\fP"
Constructor 
.br
s: impulse response 
.br
psize: partition size 
.SH "Member Function Documentation"
.PP 
.SS "template<typename S > const std::size_t \fBAurora::IR\fP< S >::nparts () const\fC [inline]\fP"
\fBIR\fP length 
.br
returns the number of partitions 
.SS "template<typename S > const std::size_t \fBAurora::IR\fP< S >::psize () const\fC [inline]\fP"
\fBIR\fP partition size 
.br
returns the size of each partition 
.SS "template<typename S > void \fBAurora::IR\fP< S >::reset (const std::vector< S > & s, std::size_t psize = \fC\fBdef_psize\fP\fP)\fC [inline]\fP"
Reset the \fBIR\fP table 
.br
s: impulse response 
.br
psize: partition size 
.SS "template<typename S > const std::vector< std::vector< std::complex< S > > > & \fBAurora::IR\fP< S >::spectrum () const\fC [inline]\fP"
\fBIR\fP spectrum access 
.br
returns a vector of impulse response partitions 

.SH "Author"
.PP 
Generated automatically by Doxygen for Aurora from the source code\&.
