.TH "BlOsc.h" 3 "Sun May 29 2022" "Version 0.1" "Aurora" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlOsc.h
.SH SYNOPSIS
.br
.PP
\fC#include 'FFT\&.h'\fP
.br
\fC#include 'Osc\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAurora::TableSet< S >\fP"
.br
.ti -1c
.RI "class \fBAurora::BlOsc< S, FN >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBAurora\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBAurora::SAW\fP = 0, \fBAurora::SQUARE\fP, \fBAurora::TRIANGLE\fP, \fBAurora::PULSE\fP }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const double \fBAurora::def_base\fP = 16\&."
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Aurora from the source code\&.
