.TH "Conv.h" 3 "Sun May 29 2022" "Version 0.1" "Aurora" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Conv.h
.SH SYNOPSIS
.br
.PP
\fC#include 'FFT\&.h'\fP
.br
\fC#include 'SndBase\&.h'\fP
.br
\fC#include <complex>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAurora::IR< S >\fP"
.br
.ti -1c
.RI "class \fBAurora::Conv< S >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBAurora\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::size_t \fBAurora::def_psize\fP = 2048"
.br
.ti -1c
.RI "const bool \fBAurora::ola\fP = 1"
.br
.ti -1c
.RI "const bool \fBAurora::ols\fP = 0"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Aurora from the source code\&.
