.TH "Env2.h" 3 "Thu Dec 30 2021" "Version 0.1" "Aurora" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Env2.h
.SH SYNOPSIS
.br
.PP
\fC#include 'SndBase\&.h'\fP
.br
\fC#include <functional>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAurora::Env< S, FN >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAurora\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename S > std::function< S(double, S, S)> \fBAurora::ads_gen\fP (const S &a, const S &d, const S &s)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Aurora from the source code\&.
