.TH "FFT.h" 3 "Sat Dec 11 2021" "Version 0.1" "Aurora" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FFT.h
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include <complex>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAurora::FFT< S >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAurora\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static uint32_t \fBAurora::np2\fP (uint32_t n)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const bool \fBAurora::packed\fP = true"
.br
.ti -1c
.RI "static bool \fBAurora::forward\fP = true"
.br
.ti -1c
.RI "static bool \fBAurora::inverse\fP = false"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Aurora from the source code\&.
