.TH "FFT.h" 3 "Sun May 29 2022" "Version 0.1" "Aurora" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FFT.h
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include <complex>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAurora::FFT< S >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBAurora\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBM_PI\fP   3\&.14159265358979323846"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static uint32_t \fBAurora::np2\fP (uint32_t n)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const bool \fBAurora::packed\fP = true"
.br
.ti -1c
.RI "static bool \fBAurora::forward\fP = true"
.br
.ti -1c
.RI "static bool \fBAurora::inverse\fP = false"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define M_PI   3\&.14159265358979323846"

.SH "Author"
.PP 
Generated automatically by Doxygen for Aurora from the source code\&.
