.TH "Fil.h" 3 "Sun May 29 2022" "Version 0.1" "Aurora" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fil.h
.SH SYNOPSIS
.br
.PP
\fC#include 'SndBase\&.h'\fP
.br
\fC#include <cmath>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAurora::Fil< S, CF, FN >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBAurora\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename S > S \fBAurora::reson\fP (S in, double *c, double *d)"
.br
.ti -1c
.RI "template<typename S > void \fBAurora::reson_cfs\fP (S f, S bw, S fs, double *c)"
.br
.ti -1c
.RI "template<typename S > void \fBAurora::reson_cfs1\fP (S f, S bw, S fs, double *c)"
.br
.ti -1c
.RI "template<typename S > void \fBAurora::reson_cfs2\fP (S f, S bw, S fs, double *c)"
.br
.ti -1c
.RI "template<typename S > S \fBAurora::dfI\fP (S in, double *c, double *d)"
.br
.ti -1c
.RI "template<typename S > S \fBAurora::dfII\fP (S in, double *c, double *d)"
.br
.ti -1c
.RI "template<typename S > void \fBAurora::lp_cfs\fP (S f, S bw, S fs, double *c)"
.br
.ti -1c
.RI "template<typename S > void \fBAurora::hp_cfs\fP (S f, S bw, S fs, double *c)"
.br
.ti -1c
.RI "template<typename S > void \fBAurora::bp_cfs\fP (S f, S bw, S fs, double *c)"
.br
.ti -1c
.RI "template<typename S > void \fBAurora::br_cfs\fP (S f, S bw, S fs, double *c)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Aurora from the source code\&.
