.TH "FourPole.h" 3 "Sun May 29 2022" "Version 0.1" "Aurora" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FourPole.h
.SH SYNOPSIS
.br
.PP
\fC#include 'SndBase\&.h'\fP
.br
\fC#include <cmath>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAurora::FourPole< S >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBAurora\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Aurora from the source code\&.
