.TH "FuncT.h" 3 "Tue Dec 7 2021" "Version 0.1" "Aurora" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FuncT.h
.SH SYNOPSIS
.br
.PP
\fC#include 'SndBase\&.h'\fP
.br
\fC#include <functional>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAurora::Func< S >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAurora\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Aurora from the source code\&.
