.TH "Osc.h" 3 "Sat Dec 4 2021" "Version 0.1" "Aurora" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Osc.h
.SH SYNOPSIS
.br
.PP
\fC#include 'SndBase\&.h'\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <functional>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAurora::Osc< S >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAurora\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename S > std::function< S(S)> \fBAurora::lookup_gen\fP (const std::vector< S > &t)"
.br
.ti -1c
.RI "template<typename S > std::function< S(S)> \fBAurora::lookupi_gen\fP (const std::vector< S > &t)"
.br
.ti -1c
.RI "template<typename S > S \fBAurora::sin\fP (double ph)"
.br
.ti -1c
.RI "template<typename S > S \fBAurora::cos\fP (double ph)"
.br
.ti -1c
.RI "template<typename S > S \fBAurora::phase\fP (double ph)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const double \fBAurora::twopi\fP = 2 * M_PI"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Aurora from the source code\&.
