.TH "SndBase.h" 3 "Wed Dec 1 2021" "Version 0.1" "Aurora" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SndBase.h
.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include <numeric>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAurora::SndBase< S >\fP"
.br
.ti -1c
.RI "class \fBAurora::BinOp< S >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAurora\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBAurora::def_vsize\fP = 64"
.br
.ti -1c
.RI "const double \fBAurora::def_sr\fP = 44100\&."
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Aurora from the source code\&.
