.TH "TwoPole.h" 3 "Fri Dec 3 2021" "Version 0.1" "Aurora" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TwoPole.h
.SH SYNOPSIS
.br
.PP
\fC#include 'SndBase\&.h'\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <functional>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAurora::TwoPole< S >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAurora\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum : int32_t { \fBAurora::LP\fP = -1, \fBAurora::HP\fP, \fBAurora::BP\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Aurora from the source code\&.
